GET http://localhost:3001/api/persons
###
DELETE  http://localhost:3001/api/persons/5

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Joseph Nakarmi",
    "number": "333"
}